### PR TITLE
remove subtitle highlight add autocomplete

### PR DESCRIPTION
**Pull request by jjw24**
remove subtitle highlight add autocomplete

### CODE REVIEW

**Comment by jjw24** [comment]
@taooceros feels like this should just point to the actual file, otherwise we need to keep updating

**Review by onesounds — APPROVED** [review]

**Comment by taooceros** [comment]
> @taooceros feels like this should just point to the actual file, otherwise we need to keep updating

Is it possible to automatically generate the docs?

**Comment by jjw24** [comment]
I think @Zeroto521 has done something like this where display is redirected internally to another file.

**Comment by taooceros** [comment]
It is easy to regenerate the docs. We just need to update it once we release a new release.
https://ejball.com/XmlDocMarkdown/

**Pull request merged**
