### PR TITLE
New doc for plugins, as per #378

### PR DESCRIPTION
**Pull request by jeremymeyers**
https://github.com/Flow-Launcher/Flow.Launcher/pull/378

### CODE REVIEW

**Comment by jjw24** [comment]
you will also need to add a reference in _sidebar.md

**Review by jjw24 — APPROVED** [review]

**Comment by jeremymeyers** [comment]
@jjw24 you have to merge the new Plugins.md file too

**Comment by Zeroto521** [comment]
Actually, it is not a good way to sync the plugin list by hand.

**Comment by jeremymeyers** [comment]
> 
> 
> Actually, it is not a good way to sync the plugin list by hand.

what do you mean?

**Comment by Zeroto521** [comment]
@jeremymeyers hi, this https://github.com/Flow-Launcher/docs/pull/18 was my meaning.

Update doc once by hand is just a start, and it never gets end.

So, a better way could be that.

**Comment by jeremymeyers** [comment]
Ah. yes this works too.

**Pull request merged**
