### PR TITLE
Added Email To plugin

### PR DESCRIPTION
**Pull request by AdamMarciniec**

### CODE REVIEW

**Comment by taooceros** [comment]
I think this list is auto fetched. So as long as the plugin is in the manifest, it will be added by the ci.

**Comment by jjw24** [comment]
Hi how's it going? Yep as @taooceros mentioned this list will be auto updated so no need to add here.

**Comment by jjw24** [comment]
Hey @AdamMarciniec, I think you meant to submit your plugin to PluginsManifest? https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest

**Comment by Echostorm44** [comment]
Yeah, I saw this list in the docs and assumed that was how you submitted them.  My bad.  
image

**Pull request closed without merging**
