### PR TITLE
Add docsify-darklight-theme

### PR DESCRIPTION
**Pull request by Garulf**
Pretty simple addition that I feel makes a lot of sense.

light-dark

### CODE REVIEW

**Comment by jjw24** [comment]
Does this mean if we use a different theme, we wont be able to stick to this darklight theme?

**Comment by Garulf** [comment]
You can switch between whatever two themes you'd like. In my PR and screenshot its alternating between simple and simple-dark.

**Comment by jjw24** [comment]
i get the switching, what i mean is if we choose a different theme like 'Simple' in above issue 29, do we loose this light dark switch ability?

**Comment by Garulf** [comment]
No, you'd just have to supply a dark variation of the theme we choose.

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
