### PR TITLE
Update C# API Docs

### PR DESCRIPTION
**Pull request by taooceros**
Update C# API Docs and add dispose information

### CODE REVIEW

**Comment by jjw24** [comment]
is there a dependency on this pr https://github.com/Flow-Launcher/Flow.Launcher/pull/938 ?

**Comment by jjw24** [comment]
can you please provide a preview in your fork

**Comment by taooceros** [comment]
> is there a dependency on this pr [Flow-Launcher/Flow.Launcher#938](https://github.com/Flow-Launcher/Flow.Launcher/pull/938) ?

not really, it is generated locally. If we want to generate this automatically we need that.

**Comment by taooceros** [comment]
https://taooceros.github.io/docs/#/API-Reference/

**Comment by taooceros** [comment]
weird the reference somehow not working when i deployed it but works locally? so weird

**Comment by taooceros** [comment]
oh it's because of windows file system is case ignore....I will fix it now

**Comment by jjw24** [comment]
hitting a lot of 404s, e.g. https://taooceros.github.io/docs/#/API-Reference/Flow.Launcher.Plugin/PluginInitContext

**Comment by jjw24** [comment]
also please update the branch to the latest

**Comment by taooceros** [comment]
Fix the issue. I thought I fix the case insensitive issue but actually not. This time actually fix it.

**Comment by taooceros** [comment]
still get some issue. let me check again

**Comment by taooceros** [comment]
ok fix it

**Comment by jjw24** [comment]
these two namespaces have 404 Flow.Launcher.Plugin.SharedCommands + Flow.Launcher.Plugin.SharedModels namespace
https://taooceros.github.io/docs/#/API-Reference/Flow.Launcher.Plugin?id=flowlauncherpluginsharedcommands-namespace

**Comment by taooceros** [comment]
> these two namespaces have 404 Flow.Launcher.Plugin.SharedCommands + Flow.Launcher.Plugin.SharedModels namespace
> https://taooceros.github.io/docs/#/API-Reference/Flow.Launcher.Plugin?id=flowlauncherpluginsharedcommands-namespace
> 
> 
> 

What?? That hasn't been fixed? I will check again🤔

**Comment by taooceros** [comment]
Oh it is fixed... I just forget to sync to my fork.

**Comment by jjw24** [comment]
how do i regenerate/update these files when need to?

**Comment by taooceros** [comment]
> how do i regenerate/update these files when need to?

https://ejball.com/XmlDocMarkdown/

**Comment by jjw24** [comment]
Yeah that's what I am thinking, set up a workflow for it

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
