### PR TITLE
Gather all docs to one rep

### PR DESCRIPTION
**Pull request by Zeroto521**
## Related issues

https://github.com/Flow-Launcher/Flow.Launcher/pull/333

## Thanks

powered by [docsify](https://docsify.js.org/)

### CODE REVIEW

**Comment by Zeroto521** [comment]
some github page settings still need to do.

image

**Comment by Zeroto521** [comment]
`Flow-Launcher/Docs` need change to `Flow-Launcher/docs`?

URL is **case sensitive**.

**Review by jjw24 — APPROVED** [review]

**Comment by jjw24** [comment]
Awesome addition, thank you

**Comment by jjw24** [comment]
is it suppose to point to a docs folder once we have one?

**Comment by Zeroto521** [comment]
@jjw24 

`/docs` means `Flow-Launcher/Flow. Launcher/docs`

`/` should be `Flow-Launcher/docs`

bug: https://github.com/Flow-Launcher/docs/runs/1917948806

**Comment by jjw24** [comment]
Ok gotcha

**Pull request merged**
